---
- name: Ensure mysql-server is installed
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql    # нужен для ansible mysql модулей
    state: present
    update_cache: false

- name: Ensure MySQL is running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: localhost
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
